### ISSUE TITLE
Can't compile kernel

### ISSUE THREAD

**Issue by yehonatan2020** [freak07/Kirisakura_Pantah#1]
Trying to compile the kernel gives this error.....

error: modpost: "pcie_sysmmu_set_use_iocc" [drivers/pci/controller/dwc/pcie-exynos-core.ko] undefined

**Comment by freak07** [comment]
Make sure to setup the build environment correctly and invoke the build for gs201/cloudripper. 
The driver containing this is only built for gs201.
Check the output of your console if you're actually building for cloudripper and not slider.
