### ISSUE TITLE
Proper support for battery idle mode

### ISSUE THREAD

**Issue by LollosoSi** [freak07/Kirisakura_Pantah#3]
Currently trying to enable idle battery mode using [ACC](https://github.com/VR-25/acc) and getting inconsistent results.
Issuing here due to the strict kernel relationship

> **Device:** Pixel 7, TQ1A.230205.002

> **Available chargers:**
> 1. Automatic
> 2. battery/bd_trickle_cnt 0 1
> 3. maxfg/offmode_charger 0 1
> 4. dc/current_max 687500 0
> 5. gcpm/constant_charge_current_max 4000000 0
> 6. gcpm/current_max 3000000 0
> 7. main-charger/current_max 3000000 0
> 8. usb/current_max 3000000 0
> 9. wireless/current_max 700000 0
> 10. battery/constant_charge_voltage 4260000 voltage_now
> 11. gcpm/constant_charge_voltage_max 4200000 voltage_now
> 12. gcpm/voltage_max 4200000 voltage_now
> 13. main-charger/voltage_max 4200000 voltage_now
> 14. pca94xx-mains/voltage_max 4175000 voltage_now

While more than one charger seems to work + idle support, the device doesn't seem to respond reliably even when tests (acc -t ..) are positive more than twice

**Notable behaviour:**
- Frequent replugs when hitting pause%
- acc -i status causes replug and battery % to fluctuate
- Charging doesn't exactly stop when plugged over the pause%
- Amperage on idle is brought to +-10mA with some chargers (expected behaviour): some others don't
- Idle mode is not detected by AccA

**Steps to reproduce:**

1. Install ACC through magisk
2. Install a terminal app such as Termux
3. Install some root explorer app such as Total Commander
4. Plug AC charger
5. in the terminal, type
`su`
`acc -t`
6. Check for working chargers (+ idle supported)
7. Test again one working charger with `acc -t (charger)`
> Example in my case: `acc -t gcpm/constant_charge_current_max 4000000 0`
8. Assign the charger using `acc -ss`
9. Using the root explorer edit `/data/adb/vr25/acc-data/config.txt` the line `prioritizeBattIdleMode=true` and save
10. Back to the terminal, type `acc` and select `start/restart daemon` then select `quit`
11. Type in your pause and resume percentages: example `acc 75 70`
12. Observe behaviour

**Expected:**
- charge to pause% then battery idle
- amperage apps should report 0 or around -10mA
- acc -i status should report Idle
- acc -i status shouldn't cause the brief percentage fluctuation
- no replugs (noticeable through sounds)

Perhaps this might come in handy:
https://github.com/xxmustafacooTR/android_kernel_samsung_universal9810/search?q=battery+idle&type=commits

Hoping for a positive response and a fix for everyone's longer battery lifespan
Have a great day

**Comment by LollosoSi** [comment]
Issue persists in Raviantah releases. There seems to be no idle mode supported chargers anymore

**Comment by freak07** [comment]
> Currently trying to enable idle battery mode using [ACC](https://github.com/VR-25/acc) and getting inconsistent results. Issuing here due to the strict kernel relationship
> 
> > **Device:** Pixel 7, TQ1A.230205.002
> 
> > **Available chargers:**
> > 
> > 1. Automatic
> > 2. battery/bd_trickle_cnt 0 1
> > 3. maxfg/offmode_charger 0 1
> > 4. dc/current_max 687500 0
> > 5. gcpm/constant_charge_current_max 4000000 0
> > 6. gcpm/current_max 3000000 0
> > 7. main-charger/current_max 3000000 0
> > 8. usb/current_max 3000000 0
> > 9. wireless/current_max 700000 0
> > 10. battery/constant_charge_voltage 4260000 voltage_now
> > 11. gcpm/constant_charge_voltage_max 4200000 voltage_now
> > 12. gcpm/voltage_max 4200000 voltage_now
> > 13. main-charger/voltage_max 4200000 voltage_now
> > 14. pca94xx-mains/voltage_max 4175000 voltage_now
> 
> While more than one charger seems to work + idle support, the device doesn't seem to respond reliably even when tests (acc -t ..) are positive more than twice
> 
> **Notable behaviour:**
> 
>     * Frequent replugs when hitting pause%
> 
>     * acc -i status causes replug and battery % to fluctuate
> 
>     * Charging doesn't exactly stop when plugged over the pause%
> 
>     * Amperage on idle is brought to +-10mA with some chargers (expected behaviour): some others don't
> 
>     * Idle mode is not detected by AccA
> 
> 
> **Steps to reproduce:**
> 
>     1. Install ACC through magisk
> 
>     2. Install a terminal app such as Termux
> 
>     3. Install some root explorer app such as Total Commander
> 
>     4. Plug AC charger
> 
>     5. in the terminal, type
>        `su`
>        `acc -t`
> 
>     6. Check for working chargers (+ idle supported)
> 
>     7. Test again one working charger with `acc -t (charger)`
> 
> 
> > Example in my case: `acc -t gcpm/constant_charge_current_max 4000000 0`
> 
>     8. Assign the charger using `acc -ss`
> 
>     9. Using the root explorer edit `/data/adb/vr25/acc-data/config.txt` the line `prioritizeBattIdleMode=true` and save
> 
>     10. Back to the terminal, type `acc` and select `start/restart daemon` then select `quit`
> 
>     11. Type in your pause and resume percentages: example `acc 75 70`
> 
>     12. Observe behaviour
> 
> 
> **Expected:**
> 
>     * charge to pause% then battery idle
> 
>     * amperage apps should report 0 or around -10mA
> 
>     * acc -i status should report Idle
> 
>     * acc -i status shouldn't cause the brief percentage fluctuation
> 
>     * no replugs (noticeable through sounds)
> 
> 
> Perhaps this might come in handy: https://github.com/xxmustafacooTR/android_kernel_samsung_universal9810/search?q=battery+idle&type=commits
> 
> Hoping for a positive response and a fix for everyone's longer battery lifespan Have a great day



> Issue persists in Raviantah releases. There seems to be no idle mode supported chargers anymore


Thanks for all the details provided, but as mentioned on XDA there´s no support for third party mods. If there´s a problem with ACC there´s nothing I can do about it really.
The charging driver is stock and I´m not going to play with it. 
On all phones that have this functionality provided by the OEM directly there needs to be support via the charging driver kernel side, the hardware side and the firmware side. 

I know there are a lot of tips and tricks floating around to get ACC working properly on Pixel 7/Pro, but I´m entirely unfamiliar with that matter. Some users got it working to their liking, I was told, but beyond that it´s probably best to seek help  at wherever ACC provides help. 
I read about adaptive battery having to be disabled, but to me it sounds like the framework and ACC are accessing the same nodes and are conflicting.

**Comment by freak07** [comment]
> Currently trying to enable idle battery mode using [ACC](https://github.com/VR-25/acc) and getting inconsistent results. Issuing here due to the strict kernel relationship
> 
> > **Device:** Pixel 7, TQ1A.230205.002
> 
> > **Available chargers:**
> > 
> > 1. Automatic
> > 2. battery/bd_trickle_cnt 0 1
> > 3. maxfg/offmode_charger 0 1
> > 4. dc/current_max 687500 0
> > 5. gcpm/constant_charge_current_max 4000000 0
> > 6. gcpm/current_max 3000000 0
> > 7. main-charger/current_max 3000000 0
> > 8. usb/current_max 3000000 0
> > 9. wireless/current_max 700000 0
> > 10. battery/constant_charge_voltage 4260000 voltage_now
> > 11. gcpm/constant_charge_voltage_max 4200000 voltage_now
> > 12. gcpm/voltage_max 4200000 voltage_now
> > 13. main-charger/voltage_max 4200000 voltage_now
> > 14. pca94xx-mains/voltage_max 4175000 voltage_now
> 
> While more than one charger seems to work + idle support, the device doesn't seem to respond reliably even when tests (acc -t ..) are positive more than twice
> 
> **Notable behaviour:**
> 
>     * Frequent replugs when hitting pause%
> 
>     * acc -i status causes replug and battery % to fluctuate
> 
>     * Charging doesn't exactly stop when plugged over the pause%
> 
>     * Amperage on idle is brought to +-10mA with some chargers (expected behaviour): some others don't
> 
>     * Idle mode is not detected by AccA
> 
> 
> **Steps to reproduce:**
> 
>     1. Install ACC through magisk
> 
>     2. Install a terminal app such as Termux
> 
>     3. Install some root explorer app such as Total Commander
> 
>     4. Plug AC charger
> 
>     5. in the terminal, type
>        `su`
>        `acc -t`
> 
>     6. Check for working chargers (+ idle supported)
> 
>     7. Test again one working charger with `acc -t (charger)`
> 
> 
> > Example in my case: `acc -t gcpm/constant_charge_current_max 4000000 0`
> 
>     8. Assign the charger using `acc -ss`
> 
>     9. Using the root explorer edit `/data/adb/vr25/acc-data/config.txt` the line `prioritizeBattIdleMode=true` and save
> 
>     10. Back to the terminal, type `acc` and select `start/restart daemon` then select `quit`
> 
>     11. Type in your pause and resume percentages: example `acc 75 70`
> 
>     12. Observe behaviour
> 
> 
> **Expected:**
> 
>     * charge to pause% then battery idle
> 
>     * amperage apps should report 0 or around -10mA
> 
>     * acc -i status should report Idle
> 
>     * acc -i status shouldn't cause the brief percentage fluctuation
> 
>     * no replugs (noticeable through sounds)
> 
> 
> Perhaps this might come in handy: https://github.com/xxmustafacooTR/android_kernel_samsung_universal9810/search?q=battery+idle&type=commits
> 
> Hoping for a positive response and a fix for everyone's longer battery lifespan Have a great day



> Issue persists in Raviantah releases. There seems to be no idle mode supported chargers anymore

Thanks for all the details provided, but as mentioned on XDA there´s no support for third party mods. If there´s a problem with ACC there´s nothing I can do about it really.
The charging driver is stock and I´m not going to play with it.
On all phones that have this functionality provided by the OEM directly there needs to be support via the charging driver kernel side, the hardware side and the firmware side.

I know there are a lot of tips and tricks floating around to get ACC working properly on Pixel 7/Pro, but I´m entirely unfamiliar with that matter. Some users got it working to their liking, I was told, but beyond that it´s probably best to seek help at wherever ACC provides help.
I read about adaptive battery having to be disabled, but to me it sounds like the framework and ACC are accessing the same nodes and are conflicting.

**Comment by LollosoSi** [comment]
Thank you for the elaborate response, really

I had 3 reasons to open the issue here rather to ACC:
1. As you mentioned, idle mode needs hardware and kernel support
2. Thus ACC is just the tool most of us use to access this specific feature (not asking support for third parties)
3. I've seen third party devs enabling this feature on a different device (linked in first post )

The proposed solution seems working at least partially, needs testing and data collection to confirm.
I understand that playing with the charging drivers at kernel level may be risky and that's not what I wanted to accomplish eventually

Note: the android 14 beta seems to be adding this specific thing, stock, might be interesting having a look into it
