### ISSUE TITLE
(Compilation error) Missing fw_sample.i

### ISSUE THREAD

**Issue by LollosoSi** [freak07/Kirisakura_Pantah#4]
Hi, I'm trying to make a custom build of the kernel in hopes to add GUD.
Compiling a clean build first, I stumbled in this error:
```
  CC [M]  google-modules/uwb/kernel/drivers/net/ieee802154/dw3000_nfcc_coex_msg.o
../google-modules/wlan/bcmdhd/bcm4389/Kbuild:33: : ** out-of-tree Kbuild BCMDHD_ROOT=../google-modules/wlan/bcmdhd/bcm4389**
  CC [M]  google-modules/wlan/bcmdhd/bcm4389/dhd_pno.o
  CC [M]  google-modules/uwb/kernel/drivers/net/ieee802154/dw3000_nfcc_coex_mcps.o
  CC [M]  google-modules/uwb/kernel/net/mcps802154/fproc.o
  CC [M]  google-modules/uwb/kernel/drivers/net/ieee802154/dw3000_pctt_mcps.o
  CC [M]  google-modules/uwb/kernel/drivers/net/ieee802154/dw3000_calib.o
  CC [M]  google-modules/wlan/bcmdhd/bcm4389/dhd_common.o
  CHK     kernel/kheaders_data.tar.xz
  CC [M]  google-modules/wlan/bcmdhd/bcm4389/dhd_ip.o
../google-modules/touch/focaltech/ft3658/focaltech_flash.c:48:10: fatal error: 'include/firmware/fw_sample.i' file not found
#include FTS_UPGRADE_FW_FILE
         ^~~~~~~~~~~~~~~~~~~
../google-modules/touch/focaltech/ft3658/focaltech_config.h:322:50: note: expanded from macro 'FTS_UPGRADE_FW_FILE'
#define FTS_UPGRADE_FW_FILE                      "include/firmware/fw_sample.i"
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1  CC [M]  google-modules/uwb/kernel/drivers/net/ieee802154/dw3000_chip_c0.o
 error generated.
make[4]: *** [../scripts/Makefile.build:321: google-modules/touch/focaltech/ft3658/focaltech_flash.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [../scripts/Makefile.build:588: google-modules/touch/focaltech/ft3658] Error 2
make[2]: *** [../scripts/Makefile.build:588: google-modules/touch/focaltech/ft3658] Error 2
make[2]: *** Waiting for unfinished jobs....
```

I'm surely missing something

Could you provide steps/requirements to build?
What I've done so far:
- From APT: `sudo apt-get install make build-essential libncurses-dev bison flex libssl-dev libelf-dev`
- Get Clang, GCC and GAS from google at https://android.googlesource.com/platform/prebuilts/
- for GCC revert to second-last commit because they removed the files (`git reset --hard <id>`)
- Get DTC from https://mirrors.edge.kernel.org/pub/software/utils/dtc/. Extract and run `make install`
Replace directories in build_kirisakura.sh
run build_kirisakura.sh

Thank you

**Comment by freak07** [comment]
Sounds to me like .i files are blacklisted via gitignore and therefore not pushed to GitHub from my local repo. 

Until I look into it, you can just check the official  Google repo for the missing firmware files.

**Comment by LollosoSi** [comment]
The sources obtained through the google developer page don't have these files
Could you specify where to find them?
I don't know how many files I am missing at the moment

[I obtained the kernel sources using:](https://source.android.com/docs/setup/build/building-pixel-kernels)
`repo init -u https://android.googlesource.com/kernel/manifest -b gs-android-gs-raviole-mainline`
`repo sync -c --no-tags -j8`

Tried merging the files with this source but I just caused more errors

**Comment by freak07** [comment]
> The sources obtained through the google developer page don't have these files Could you specify where to find them? I don't know how many files I am missing at the moment
> 
> [I obtained the kernel sources using:](https://source.android.com/docs/setup/build/building-pixel-kernels) `repo init -u https://android.googlesource.com/kernel/manifest -b gs-android-gs-raviole-mainline` `repo sync -c --no-tags -j8`
> 
> Tried merging the files with this source but I just caused more errors

the repos from google have the file. 
you are able to find it here:
https://android.googlesource.com/kernel/google-modules/touch/focaltech_touch/+/refs/tags/android-14.0.0_r0.14/ft3658/include/firmware
and then just add it to the correct place.


In the meantime I adjusted gitignore and updated my tree too.
